# Generated by Django 5.2.7 on 2025-11-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='University',
            new_name='university',
        ),
    ]
